### ISSUE TITLE
investigate on broken deployment

### ISSUE THREAD

**Issue by marco-ippolito** [nearform/zoom-shuffle-bot#233]
deployement failed: https://github.com/nearform/zoom-shuffle-bot/runs/8270518564?check_suite_focus=true
requires further investigation

**Comment by simoneb** [comment]
@marco-ippolito see another similar failure here: https://github.com/nearform/github-app-notify-twitter/runs/8275410760?check_suite_focus=true. It looks like it's the same pattern, so probably also the same root cause
