### ISSUE TITLE
Zoom signature check missing timestamp verification

### ISSUE THREAD

**Issue by Gby56** [nearform/zoom-shuffle-bot#480]
This might allow for replay attacks

https://hookdeck.com/webhooks/guides/webhook-security-vulnerabilities-guide#timestamped-signatures

https://github.com/nearform/zoom-shuffle-bot/blob/5eb4dcccddd09de84283327b6b7a74b2330abb4f/plugins/verifyRequest.js#L5

**Comment by ollyjohn** [comment]
Blocked temporarily while waiting for a permissions increase on Zoom so I can install the bot for local testing
