### ISSUE TITLE
Zoom validation review

### ISSUE THREAD

**Issue by simoneb** [nearform/zoom-shuffle-bot#483]
![image](https://github.com/nearform/zoom-shuffle-bot/assets/20181/a90461cb-2eee-47a1-91d9-14fc021ec8ac)

**Comment by ollyjohn** [comment]
As far as I can tell, we're already doing it the new way
https://github.com/nearform/zoom-shuffle-bot/blob/master/helpers/crypto.js#L23-L33

**Comment by simoneb** [comment]
Thanks, I'll close this then 👌
